// generated by
// z_seq_1_to_4 = [...Array(5).keys()].slice(1)
// p_seq_0_to_4 = [...Array(5).keys()]
// keys = z_seq_1_to_4.flatMap(z=>p_seq_0_to_4.map(p=> `direction_sv_zl${z}${p<4?'_p' + p:''}`))
// console.log(keys.map(k => `import ${k} from '@/assets/images/streetview/${k}.png'`).join('\n'))

import direction_sv_zl1_p0 from '@/assets/images/streetview/direction_sv_zl1_p0.png'
import direction_sv_zl1_p1 from '@/assets/images/streetview/direction_sv_zl1_p1.png'
import direction_sv_zl1_p2 from '@/assets/images/streetview/direction_sv_zl1_p2.png'
import direction_sv_zl1_p3 from '@/assets/images/streetview/direction_sv_zl1_p3.png'
import direction_sv_zl1 from '@/assets/images/streetview/direction_sv_zl1.png'
import direction_sv_zl2_p0 from '@/assets/images/streetview/direction_sv_zl2_p0.png'
import direction_sv_zl2_p1 from '@/assets/images/streetview/direction_sv_zl2_p1.png'
import direction_sv_zl2_p2 from '@/assets/images/streetview/direction_sv_zl2_p2.png'
import direction_sv_zl2_p3 from '@/assets/images/streetview/direction_sv_zl2_p3.png'
import direction_sv_zl2 from '@/assets/images/streetview/direction_sv_zl2.png'
import direction_sv_zl3_p0 from '@/assets/images/streetview/direction_sv_zl3_p0.png'
import direction_sv_zl3_p1 from '@/assets/images/streetview/direction_sv_zl3_p1.png'
import direction_sv_zl3_p2 from '@/assets/images/streetview/direction_sv_zl3_p2.png'
import direction_sv_zl3_p3 from '@/assets/images/streetview/direction_sv_zl3_p3.png'
import direction_sv_zl3 from '@/assets/images/streetview/direction_sv_zl3.png'
import direction_sv_zl4_p0 from '@/assets/images/streetview/direction_sv_zl4_p0.png'
import direction_sv_zl4_p1 from '@/assets/images/streetview/direction_sv_zl4_p1.png'
import direction_sv_zl4_p2 from '@/assets/images/streetview/direction_sv_zl4_p2.png'
import direction_sv_zl4_p3 from '@/assets/images/streetview/direction_sv_zl4_p3.png'
import direction_sv_zl4 from '@/assets/images/streetview/direction_sv_zl4.png'

// console.log(keys.join(',\n'))

export default {
  direction_sv_zl1_p0,
  direction_sv_zl1_p1,
  direction_sv_zl1_p2,
  direction_sv_zl1_p3,
  direction_sv_zl1,
  direction_sv_zl2_p0,
  direction_sv_zl2_p1,
  direction_sv_zl2_p2,
  direction_sv_zl2_p3,
  direction_sv_zl2,
  direction_sv_zl3_p0,
  direction_sv_zl3_p1,
  direction_sv_zl3_p2,
  direction_sv_zl3_p3,
  direction_sv_zl3,
  direction_sv_zl4_p0,
  direction_sv_zl4_p1,
  direction_sv_zl4_p2,
  direction_sv_zl4_p3,
  direction_sv_zl4,
}
